[package]
name = "data_compressing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.2"
flate2 = "1.0.30"
tar = "0.4.40"
xz2 = "0.1.7"